# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'introducao.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.btnBotao1 = QtWidgets.QPushButton(Form)
        self.btnBotao1.setGeometry(QtCore.QRect(90, 230, 89, 25))
        self.btnBotao1.setObjectName("btnBotao1")
        self.lblTexto = QtWidgets.QLabel(Form)
        self.lblTexto.setGeometry(QtCore.QRect(180, 70, 71, 21))
        self.lblTexto.setObjectName("lblTexto")
        self.btnBotao2 = QtWidgets.QPushButton(Form)
        self.btnBotao2.setGeometry(QtCore.QRect(230, 230, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btnBotao2.setFont(font)
        self.btnBotao2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBotao2.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.btnBotao2.setObjectName("btnBotao2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnBotao1.setText(_translate("Form", "Botão 1"))
        self.lblTexto.setText(_translate("Form", "Texto"))
        self.btnBotao2.setText(_translate("Form", "Botão 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
